name: Build SunamoStringParts

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoStringParts
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringParts/SunamoStringParts.csproj

    - name: Build
      run: dotnet build SunamoStringParts/SunamoStringParts.csproj --configuration Release --no-restore

  test:
    name: Test SunamoStringParts.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringParts.Tests/SunamoStringParts.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoStringParts.Tests/SunamoStringParts.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoStringParts.Tests/SunamoStringParts.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
